import json
from pathlib import Path

import pandas as pd
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_REPORT = PROJECT_ROOT / "output-json" / "triage_lockdown_report.json"
SAMPLE_REPORT = PROJECT_ROOT / "sample-data" / "triage_lockdown_report.sample.json"


st.set_page_config(page_title="DFIR Memory Triage Dashboard", layout="wide")
st.title("DFIR Memory Triage Dashboard")
st.caption("Volatility3 triage results generated by an n8n automation workflow.")


@st.cache_data
def load_report(path: Path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


report_path = OUTPUT_REPORT if OUTPUT_REPORT.exists() else SAMPLE_REPORT

try:
    data = load_report(report_path)
except FileNotFoundError:
    st.error("No triage report found. Run the n8n workflow or add a sample report.")
    st.stop()


artifacts = data.get("artifacts", {})

processes = artifacts.get("process_list", [])
network_connections = artifacts.get("network_connections", [])
injected_memory = artifacts.get("injected_memory", [])

col1, col2, col3 = st.columns(3)
col1.metric("Processes", len(processes))
col2.metric("Network Connections", len(network_connections))
col3.metric("Injected Memory Regions", len(injected_memory))

st.divider()
st.subheader("Network Connections")

network_df = pd.DataFrame(network_connections)
if network_df.empty:
    st.info("No network connections found in the current report.")
else:
    st.dataframe(network_df, use_container_width=True)

st.divider()
st.subheader("Process List")

process_df = pd.DataFrame(processes)
if process_df.empty:
    st.info("No process list entries found in the current report.")
else:
    st.dataframe(process_df, use_container_width=True)

st.divider()
st.subheader("Injected Memory Findings")

malfind_df = pd.DataFrame(injected_memory)
if malfind_df.empty:
    st.info("No injected memory findings found in the current report.")
else:
    suspicious_columns = [
        column
        for column in ["PID", "Process", "Protection", "Tag", "Notes", "Start VPN", "End VPN"]
        if column in malfind_df.columns
    ]
    st.warning("Review memory regions with executable write permissions, unusual tags, or PE headers.")
    st.dataframe(malfind_df[suspicious_columns], use_container_width=True)

st.divider()
st.caption(f"Report source: {report_path}")
